config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get '/explore', to: 'posts#explore', as: 'explore_posts'
  resources :posts do
    get '/comments/page/:comment_page', to: 'comments#index', as: 'more_comments'
  	resources :comments
  	member do
  		put 'like', to: 'posts#like', as: 'like'
  		put 'unlike', to: 'posts#unlike', as: 'unlike'
  	end
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  get ':user_name', to: 'users#index', as: 'user_posts'
  put ':user_name/follow', to: 'users#follow', as: 'follow_user'
  put ':user_name/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get ':user_name/followers', to: 'users#followers', as: 'user_followers'
  get ':user_name/following', to: 'users#following', as: 'user_following'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post

	def index
		if params[:comment_page].blank?
			@comments = @post.comments.order("created_at DESC")
		else
			limit = params[:comment_page]
			@comments = @post.comments.order("created_at DESC").take limit
		end
		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end
	end

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		else
			flash[:alert] = "Check the comment form, something went horribly wrong"
			render root_path
		end
	end

	def destroy
		@comment = Comment.find(params[:id])

		if @comment.user == current_user
			@comment.destroy
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_post
		@post = Post.find(params[:post_id])
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<div class="user-name">
		<%= link_to comment.user.user_name, user_posts_path(comment.user) %>
	</div>
	<div class="comment-content">
		<%= comment.content %>
	</div>
	<% if comment.user == current_user %>
		<%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, remote: true do %>
			<span class="glyphicon glyphicon-remove delete-comment"></span>
		<% end %>
	<% end %>
</div>

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
	<%= render 'comments/comment', post: post, comment: comment %>
<% end %>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').prepend("<%= j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('');

<% if @post.comments.count > 5 %>
	$('#comments_<%= @post.id %> .comment').last().remove();

	if($('#comments_<%= @post.id %> div').last().attr('class') != 'see-comments-wrapper')
		$('#comments_<%= @post.id %>').append("<%= j render 'posts/see_comments_wrapper', post: @post %>")
<% else %>
	$('#comments_<%= @post.id %> .see-all').remove();
<% end %>

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.last_comments(Post.comment_limit), post: @post, comment: @comment %>");
<% if @post.comments.count > 5 %>
	if($('#comments_<%= @post.id %>').last().attr('class') != 'see-comments-wrapper')
		$('#comments_<%= @post.id %>').append("<%= j render 'posts/see_comments_wrapper', post: @post %>")
<% end %>

app/views/comments/index.js.erb
comments = $('#comments_<%= @post.id %>');
comments.html("<%= j render @comments, post: @post, comment: @comment %>");

current_comments = ($('#comments_<%= @post.id %>').children('.comment').length);
total_comments = ("<%= @post.comments.count %>");

if (comments.children('div').last().attr('class') != 'see-comments-wrapper' && current_comments < total_comments) {
	$('#comments_<%= @post.id %>').append("<%= j render 'posts/see_comments_wrapper', post: @post %>")
}