config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get '/explore', to: 'posts#explore', as: 'explore_posts'
  resources :posts do
    get '/comments/page/:comment_page', to: 'comments#index', as: 'more_comments'
  	resources :comments
  	member do
  		put 'like', to: 'posts#like', as: 'like'
  		put 'unlike', to: 'posts#unlike', as: 'unlike'
  	end
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  get ':user_name', to: 'users#index', as: 'user_posts'
  put ':user_name/follow', to: 'users#follow', as: 'follow_user'
  put ':user_name/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get ':user_name/followers', to: 'users#followers', as: 'user_followers'
  get ':user_name/following', to: 'users#following', as: 'user_following'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_attached_file :avatar, styles: { thumbnail: "48x48#", small: "100x100#" }, :default_url => "/images/:style/missing-avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_voter

  acts_as_follower
  acts_as_followable

  # Virtual attribute for authenticating by either username or email
  # This is an addition to a real persisted field, 'user_name'
  attr_accessor :login

  def self.find_for_database_authentication warden_conditions
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
  		where(conditions.to_hash).where(["user_name = :value OR lower(email) = lower(:value)", { value: login }]).first
  	else
  		conditions[:email].downcase! if conditions[:email]
  		where(conditions.to_hash).first
  	end
  end

  def to_param
    user_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :find_user, only: [ :index, :followers, :following ]
	before_action :set_other_user, only: [ :follow, :unfollow ]

	def index
		@posts = @user.posts.order("created_at DESC").page(params[:page])
	end

	def follow
		current_user.follow @other_user
		respond_to do |format|
			format.html { redirect_to :back }
			format.js
		end
	end

	def unfollow
		current_user.stop_following @other_user
		respond_to do |format|
			format.html { redirect_to :back }
			format.js
		end
	end

	def followers
		@users = @user.followers
	end

	def following
		@users = @user.all_following
	end

	private

	def find_user
		@user = User.find_by_user_name(params[:user_name])
	end

	def set_other_user
		@other_user = User.find_by_user_name(params[:user_name])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<div class="title title-follow">FOLLOW</div>
<%= link_to follow_user_path(user), method: :put, class: 'follow', id: "@follow_#{user.id}" do %>
	<span class="glyphicon glyphicon-plus"></span>
<% end %>

app/views/users/_info.html.erb
<div class="text-center profile-header">
	<h2><%= user.user_name %></h2>
	<div class="info">
		<div class="col-sm-4 border-right">
			<%= pluralize(user.posts.count, 'post') %>
		</div>
		<div class="col-sm-4 border-right">
			<%= link_to pluralize(user.followers_count, 'follower'), user_followers_path %>
		</div>
		<div class="col-sm-4">
			<%= link_to "#{@user.follow_count} following", user_following_path %>
		</div>
	</div>
</div>

app/views/users/_unfollow_button.html.erb
<div class="title title-unfollow">UNFOLLOW</div>
<%= link_to unfollow_user_path(user), method: :put, class: 'unfollow', id: "unfollow_#{user.id}" do %>
	<span class="glyphicon glyphicon-remove"></span>
<% end %>

app/views/users/_users_list.html.erb
<div class="follow-info">
	<% unless users.empty? %>
		<ul class="list-unstyled">
			<% users.each do |user| %>
				<li>
					<div class="thumb-img col-sm-2">
						<%= link_to user_posts_path(user) do %>
							<%= image_tag(user.avatar.url(:thumbnail), size: "32", class: 'img-circle') %>
						<% end %>
					</div>
					<div class="user-name col-sm-7">
						<%= link_to user_posts_path(user) do %>
							<%= user.user_name %>
						<% end %>
					</div>
					<% if current_user != user %>
						<div class="col-sm-3">
							<div class="follow-wrapper">
								<% if current_user.following? user %>
									<%= link_to "Unfollow", unfollow_user_path(user), method: :put, class: 'unfollow', remote: true, id: "unfollow_#{user.id}" %>
								<% else %>
									<%= link_to"Follow", follow_user_path(user), method: :put, class: 'follow', remote: true, id: "follow_#{user.id}" %>
								<% end %>
							</div>
						</div>						
					<% end %>
					<div class="clearfix"></div>
				</li>
			<% end %>
		</ul>
	<% else %>
		<div class="empty">
			None found :-(
		</div>
	<% end %>
</div>
<div class="text-center back"><%= link_to "Back", user_posts_path(current_user) %></div>

app/views/users/follow.js.erb
$('#follow_<%= @other_user.id %>')
	.removeClass("follow")
	.addClass("unfollow")
	.html("Unfollow")
	.attr("href", "<%= unfollow_user_path(@other_user) %>")
	.attr("id", "unfollow_<%= @other_user.id %>");

app/views/users/followers.html.erb
<%= render 'info', user: @user %>

<div class="follow-info-container">
	<h3>Followers</h3>
	<%= render 'users_list', users: @users %>
</div>

app/views/users/following.html.erb
<%= render 'info', user: @user %>

<div class="row follow-info-container">
	<h3>Following</h3>
	<%= render 'users_list', users: @users %>
</div>

app/views/users/index.html.erb
<div class="row">
	<%= render 'info', user: @user %>
</div>
<% if current_user != @user %>
	<div class="follow-single">
		<div class="follow-wrapper">
			<% if current_user.following? @user %>
				<%= render 'unfollow_button', user: @user %>
			<% else %>
				<%= render 'follow_button', user: @user %>
			<% end %>
		</div>
	</div>
<% end %>
<%= render 'posts/posts', posts: @posts %>

app/views/users/index.js.erb
<%= render partial: 'posts/more_comments', locals: { posts: @posts } %>

app/views/users/unfollow.js.erb
$('#unfollow_<%= @other_user.id %>')
	.removeClass("unfollow")
	.addClass("follow")
	.html("Follow")
	.attr("href", "<%= follow_user_path(@other_user) %>")
	.attr("id", "follow_<%= @other_user.id %>");