config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get '/explore', to: 'posts#explore', as: 'explore_posts'
  resources :posts do
    get '/comments/page/:comment_page', to: 'comments#index', as: 'more_comments'
  	resources :comments
  	member do
  		put 'like', to: 'posts#like', as: 'like'
  		put 'unlike', to: 'posts#unlike', as: 'unlike'
  	end
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  get ':user_name', to: 'users#index', as: 'user_posts'
  put ':user_name/follow', to: 'users#follow', as: 'follow_user'
  put ':user_name/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get ':user_name/followers', to: 'users#followers', as: 'user_followers'
  get ':user_name/following', to: 'users#following', as: 'user_following'
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :user_id, presence: true
	validates :image, presence: true
	validates :caption, length: { minimum: 3, maximum: 300 }

	has_attached_file :image, styles: { small: "350x", medium: "640x", big: "900x" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	belongs_to :user
	has_many :comments, dependent: :destroy

	acts_as_votable

	@@comment_limit = 5

	def last_comments limit
		comments.order("created_at DESC").take(limit)
	end

	def self.comment_limit
		@@comment_limit
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [ :show, :edit, :update, :destroy, :like, :unlike, :load_more_comments ]
	before_action :owned_post, only: [ :edit, :update, :destroy ]
	before_action :authenticate_user!

	def index
		@posts = Post.where(user_id: current_user.all_following.collect(&:id)
			.push(current_user.id))
			.order("created_at DESC")
			.page(params[:page])

		if params[:limit]
			@posts = @posts.per params[:limit]
		end
	end

	def explore
		@q = Post.ransack params[:q]
		if @q
			100.times{puts "1 - #{params[:q]}"}
			@posts = @q.result(distinct: true)
		else
			100.times{puts "2 - #{params[:q]}"}
			@posts = Post.all
		end
		@posts = @posts.order("created_at DESC").page(params[:page])
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build post_params

		if @post.save
			flash[:success] = "Your post has been created!"
			redirect_to root_path
		else
			flash.now[:alert] = "Your new post couldn't be created! Please check the form"
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update post_params
			flash[:success] = "Post updated"
			redirect_to post_path(@post)
		else
			flash.now[:alert] = "Update failed. Please check the form"
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		flash[:notice] = "Post deleted"
		redirect_to posts_path
	end

	def like
		@post.liked_by current_user
		respond_to do |format|
			format.html { redirect_to :back }
			format.js
		end
	end

	def unlike
		@post.unliked_by current_user
		respond_to do |format|
			format.html { redirect_to :back }
			format.js
		end
	end

	private

	def post_params
		params.require(:post).permit(:image, :caption)
	end

	def find_post
		@post = Post.find(params[:id])
	end

	def owned_post
		unless current_user == @post.user
			flash[:alert] = "That post doesn't belong to you!"
			redirect_to root_path
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
	<div class="post">
		<%= form_image_select @post %>
		<%= simple_form_for @post, html: { multipart: true, autocomplete: :off } do |f| %>
			<div class="row">
				<div class="col-md-12 text-center">
					<%= f.error_notification %>
				</div>
			</div>
			<div class="container-fluid">
				<div class="form-group text-center">
					<h4>Upload an image</h4>
					<%= f.input :image, label: false %>
				</div>
				<div class="form-group text-center">
					<%= f.input :caption, label: false, placeholder: 'Add your caption' %>
				</div>
				<div class="form-group text-center">
					<%= f.button :submit, class: 'btn-success btn-block', data: { disable_with: 'Please wait...' } %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/_list.html.erb
<div id="posts">
	<% posts.each do |post| %>
		<%= render 'posts/post', post: post %>
	<% end %>
</div>

<div id="paginator">
	<%= link_to_next_page posts, 'LOAD MORE', remote: true, id: 'load_more', class: 'hidden', params: params %>
</div>

app/views/posts/_more_comments.js.erb
$('#paginator').remove();
$('#posts').append("<%= j render 'posts/list', posts: posts %>");

app/views/posts/_post.html.erb
<div class="posts-wrapper">
	<div class="post">
		<div class="post-head">
			<%= link_to user_posts_path(post.user) do %>
				<div class="thumb-img col-sm-1 col-xs-2">
					<%= image_tag(post.user.avatar.url(:thumbnail), class: 'img-circle') %>
				</div>
				<div class="user-name col-sm-6 col-xs-3">
					<%= post.user.user_name %>
				</div>
			<% end %>
			<div class="time-ago col-sm-5 col-xs-7">
				<%= time_ago_in_words post.created_at %> ago
			</div>
		</div>
		<div class="image center-block">
			<%= link_to (image_tag post.image.url(:medium), class: 'img-responsive'), post_path(post) %>
		</div>
		<div class="post-bottom">
			<div class="likes" id="likes_<%= post.id %>">
				<%= pluralize(number_to_human(post.get_likes.size, precision: 5), 'like') %>
			</div>
			<div class="caption">
				<div class="user-name">
					<%= link_to post.user.user_name, user_posts_path(post.user) %>
				</div>
				<%= post.caption %>
			</div>
			<% if post.comments %>
				<div>
					<div id="comments_<%= post.id %>">
						<%= render 'comments/comments', post: post, comments: post.last_comments(Post.comment_limit) %>
						<% if post.comments.count > Post.comment_limit %>
							<%= render 'posts/see_comments_wrapper', post: post %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
		<div class="comment-like-form row">
			<div class="like-button col-sm-1">
				<% unless current_user.voted_for? post %>
					<%= link_to like_post_path(post), method: :put, remote: true do %>
						<span class="glyphicon glyphicon-heart-empty" id="like_button_<%= post.id %>"></span>
					<% end %>
				<% else %>
					<%= link_to unlike_post_path(post), method: :put, remote: true do %>
						<span class="glyphicon glyphicon-heart" id="like_button_<%= post.id %>"></span>
					<% end %>
				<% end %>
			</div>
			<div class="comment-form col-sm-11">
				<%= form_for([ post, post.comments.build ], remote:true) do |f| %>
					<%= f.text_field :content, placeholder: 'Add a comment...', id: "comment_content_" + post.id.to_s, autocomplete: :off %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/_posts.html.erb
<div class="display-wrapper">
	<span class="glyphicon glyphicon-th-list disabled" id="list-display"></span>
	<span class="glyphicon glyphicon-th" id="mosaic-display"></span>
</div>

<%= render 'posts/list', posts: @posts %>

app/views/posts/_see_all_comments.html.erb
<%= link_to "See all", post_comments_path(post), remote: true, class: 'see-all' %>

app/views/posts/_see_comments_wrapper.html.erb
<div class="see-comments-wrapper">
	<%= render 'posts/see_all_comments', post: post %> |
	<%= render 'posts/see_more_comments', post: post %>
</div>

app/views/posts/_see_more_comments.html.erb
<%= link_to "See more...", post_more_comments_path(post, params[:comment_page].blank? ? Post.comment_limit*2 : params[:comment_page].to_i + Post.comment_limit), remote: true, class: 'see-more' %>

app/views/posts/edit.html.erb
<%= render 'form' %>

<div class="text-center edit-links">
	<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
	|
	<%= link_to "Cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<%= render 'posts', posts: @posts %>

app/views/posts/like.js.erb
$('#likes_<%= @post.id %>').html("<%= pluralize(@post.get_likes.size, 'like')%>");
$('#like_button_<%= @post.id %>').removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$('#like_button_<%= @post.id %>').parent().attr('href', "<%= unlike_post_path(@post) %>")

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>

<div class="text-center edit-links">
	<%= link_to "Home", posts_path %>
	<% if current_user == @post.user %>
		|
		<%= link_to "Edit", edit_post_path(@post) %>
	<% end %>
</div>

app/views/posts/unlike.js.erb
$('#likes_<%= @post.id %>').html("<%= pluralize(@post.get_likes.size, 'like')%>");
$('#like_button_<%= @post.id %>').removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$('#like_button_<%= @post.id %>').parent().attr('href', "<%= like_post_path(@post) %>")