config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get '/explore', to: 'posts#explore', as: 'explore_posts'
  resources :posts do
    get '/comments/page/:comment_page', to: 'comments#index', as: 'more_comments'
  	resources :comments
  	member do
  		put 'like', to: 'posts#like', as: 'like'
  		put 'unlike', to: 'posts#unlike', as: 'unlike'
  	end
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  get ':user_name', to: 'users#index', as: 'user_posts'
  put ':user_name/follow', to: 'users#follow', as: 'follow_user'
  put ':user_name/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  get ':user_name/followers', to: 'users#followers', as: 'user_followers'
  get ':user_name/following', to: 'users#following', as: 'user_following'
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
	<div class="navbar-container">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" data-target="#navbar-collapse" data-toggle="collapse" type="button">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div class="navbar-brand">
				<div class="brand-wrapper">
					<%= link_to root_path do %>
						<%= image_tag('logo.svg', size: "40", class: 'logo') %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="profile-nav-li">
						<span class="glyphicon glyphicon-zoom-in maximize"></span>
						<%= link_to user_posts_path(current_user) do %>
							<%= image_tag(current_user.avatar.url(:small), size: "40", class: "img-circle") %>
						<% end %>
					</li>
					<li><%= link_to "Explore", explore_posts_path %></li>
					<li><%= link_to "Upload Photo", new_post_path %></li>
					<li><%= link_to "My Account", edit_user_registration_path %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Login", new_user_session_path %></li>
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="<%= context_container %>">
	<% unless controller_name == 'sessions' && action_name == 'new' %>
		<% flash.each do |name, msg| %>
			<div class="<%= context_alert_container %>">
				<%= content_tag :div, msg, class: [ 'alert', alert_for(name), 'text-center' ] %>
			</div>
		<% end %>
	<% end %>
	<% if user_signed_in? %>
		<div class="col-sm-12 profile-float-container">
			<div class="profile-float-wrapper">
				<span class="glyphicon glyphicon-zoom-out minimize"></span>
				<%= link_to user_posts_path(current_user) do %>
					<%= image_tag(current_user.avatar.url(:small), class: 'img-circle profile-nav-img') %>
				<% end %>
			</div>
		</div>
	<% end %>
	
	<%= yield %>
	
</div>
</body>
</html>